staging.site.com:
  stage: staging
  hostname: site.com
  roles: website
  deploy_path: ~/subsites/staging.site.com
site.com:
  stage: prod
  hostname: site.com
  roles: website
  deploy_path: ~/subsites/site.com